const GROUPS={SHOOTING:['closeShot','midRangeShot','threePointShot','freeThrow','shotIQ','offensiveConsistency'],FINISHING:['layup','standingDunk','drivingDunk','postHook','postFade','postControl','drawFoul','hands'],PLAYMAKING:['passAccuracy','ballHandle','speedWithBall','passIQ','passVision'],DEFENSE:['interiorDefense','perimeterDefense','steal','block','helpDefenseIQ','passPerception','defensiveConsistency'],REBOUNDING:['offensiveRebound','defensiveRebound'],ATHLETICISM:['speed','strength','agility','vertical','stamina','hustle','durability'],INTANGIBLES:['intangibles'],POTENTIAL:['potential']};
const label=k=>k.replace(/([A-Z])/g,' $1').trim().toUpperCase();
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/gi,'').toLowerCase();
let ratings=null,index=null,observer=null,scheduled=false;
function find(name){if(!ratings)return null;return ratings[name]||index?.get(norm(name))||null}
function ratingForRow(row){const name=row.querySelector('.grow b')?.textContent,r=find(name);return Number.isFinite(r?.rating2k)?r.rating2k:Number(row.querySelector('.ovr')?.textContent)||0}
function sortRosters(){const rows=[...document.querySelectorAll('.rosterRow')];const parents=new Set(rows.map(r=>r.parentElement).filter(Boolean));for(const parent of parents){const group=rows.filter(r=>r.parentElement===parent);if(group.length<2)continue;group.sort((a,b)=>ratingForRow(b)-ratingForRow(a)||(a.querySelector('.grow b')?.textContent||'').localeCompare(b.querySelector('.grow b')?.textContent||''));for(const row of group)parent.appendChild(row)}}
function paint(){scheduled=false;if(!ratings)return;document.querySelectorAll('.rosterRow').forEach(row=>{const name=row.querySelector('.grow b')?.textContent,r=find(name);if(r){const o=row.querySelector('.ovr');if(o&&o.textContent!==String(r.rating2k))o.textContent=r.rating2k}});sortRosters();const hero=document.querySelector('.playerHero');if(!hero)return;const name=hero.querySelector('h1')?.textContent,r=find(name);if(!r)return;const o=hero.querySelector('.bigOvr');if(o&&o.dataset.rating2k!==String(r.rating2k)){o.dataset.rating2k=String(r.rating2k);o.innerHTML=`${r.rating2k} <small>OVR</small>`}if(hero.dataset.full2k==='1')return;hero.dataset.full2k='1';const main=hero.closest('main');if(!main)return;main.querySelectorAll('.ratingGrid').forEach(g=>{const s=g.previousElementSibling;if(s?.classList.contains('section'))s.remove();g.remove()});const html=Object.entries(GROUPS).map(([group,keys])=>`<div class="section">${group} — NBA 2K27</div><div class="ratingGrid">${keys.filter(k=>Number.isFinite(r.ratings?.[k])).map(k=>`<div><span>${label(k)}</span><b>${r.ratings[k]}</b></div>`).join('')}</div>`).join('');main.insertAdjacentHTML('beforeend',html)}
function schedulePaint(){if(scheduled)return;scheduled=true;requestAnimationFrame(paint)}
async function load(){try{const mod=await import('../data/2k27-ratings.js?v=0.5.7');ratings=mod.RATINGS_2K27;index=new Map(Object.entries(ratings).map(([n,r])=>[norm(n),r]));paint();const app=document.querySelector('#app');if(app){observer=new MutationObserver(schedulePaint);observer.observe(app,{childList:true,subtree:true})}}catch(e){console.error('NBA 2K27 ratings load failed',e)}}
if('requestIdleCallback'in window)requestIdleCallback(load,{timeout:1500});else setTimeout(load,250);