const GROUPS={SHOOTING:['closeShot','midRangeShot','threePointShot','freeThrow','shotIQ','offensiveConsistency'],FINISHING:['layup','standingDunk','drivingDunk','postHook','postFade','postControl','drawFoul','hands'],PLAYMAKING:['passAccuracy','ballHandle','speedWithBall','passIQ','passVision'],DEFENSE:['interiorDefense','perimeterDefense','steal','block','helpDefenseIQ','passPerception','defensiveConsistency'],REBOUNDING:['offensiveRebound','defensiveRebound'],ATHLETICISM:['speed','strength','agility','vertical','stamina','hustle','durability'],INTANGIBLES:['intangibles'],POTENTIAL:['potential']};
const label=k=>k.replace(/([A-Z])/g,' $1').trim().toUpperCase();
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/gi,'').toLowerCase();
let ratings=null,index=null,painting=false;
function find(name){if(!ratings)return null;return ratings[name]||index?.get(norm(name))||null}
function paint(){if(!ratings||painting)return;painting=true;try{
 document.querySelectorAll('.rosterRow').forEach(row=>{const name=row.querySelector('.grow b')?.textContent,r=find(name);if(r){const o=row.querySelector('.ovr');if(o)o.textContent=r.rating2k;row.dataset.rating2k=String(r.rating2k)}});
 const hero=document.querySelector('.playerHero');if(hero){const name=hero.querySelector('h1')?.textContent,r=find(name);if(r&&hero.dataset.full2k!=='1'){hero.dataset.full2k='1';const o=hero.querySelector('.bigOvr');if(o)o.innerHTML=`${r.rating2k} <small>OVR</small>`;const main=hero.closest('main');if(main){main.querySelectorAll('.ratingGrid').forEach(g=>{const s=g.previousElementSibling;if(s?.classList.contains('section'))s.remove();g.remove()});const html=Object.entries(GROUPS).map(([group,keys])=>`<div class="section">${group} — NBA 2K27</div><div class="ratingGrid">${keys.filter(k=>Number.isFinite(r.ratings?.[k])).map(k=>`<div><span>${label(k)}</span><b>${r.ratings[k]}</b></div>`).join('')}</div>`).join('');main.insertAdjacentHTML('beforeend',html)}}}
}finally{painting=false}}
async function load(){try{const mod=await import('../data/2k27-ratings.js?v=0.5.4');ratings=mod.RATINGS_2K27;index=new Map(Object.entries(ratings).map(([n,r])=>[norm(n),r]));paint();new MutationObserver(()=>paint()).observe(document.querySelector('#app'),{childList:true,subtree:true})}catch(e){console.error('NBA 2K27 ratings load failed',e)}}
if('requestIdleCallback'in window)requestIdleCallback(load,{timeout:1500});else setTimeout(load,250);