const VERSION='0.6.149';
const BUILD_KEY='nba-gm-build';
const versionEl=document.querySelector('[data-version]');if(versionEl)versionEl.textContent=`VERSION ${VERSION}`;
try{localStorage.setItem(BUILD_KEY,VERSION)}catch{}
document.querySelector('#enterGame')?.addEventListener('click',()=>{document.querySelector('#launch')?.remove();document.body.classList.remove('launching')});
function freshRoot(version){const u=new URL('./',document.baseURI);u.search='';u.searchParams.set('v',version);u.searchParams.set('t',Date.now());return u.href}
async function purgeOldRuntime(){try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('nba-gm-')&&k!==`nba-gm-${VERSION}`).map(k=>caches.delete(k)))}catch{}}
async function registerUpdater(){if(!('serviceWorker'in navigator))return null;try{const reg=await navigator.serviceWorker.register(`./sw.js?v=${VERSION}&t=${Date.now()}`,{scope:'./',updateViaCache:'none'});await reg.update();return reg}catch(e){console.warn('service worker registration failed',e);return null}}
async function hardUpdate(version,button){button.disabled=true;button.textContent='APPLYING UPDATE…';try{localStorage.setItem(BUILD_KEY,version)}catch{}try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('nba-gm-')).map(k=>caches.delete(k)));const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}catch{}const u=freshRoot(version);location.replace(u)}
async function checkForUpdate(button){const original=button.dataset.label||button.textContent;button.dataset.label=original;button.disabled=true;button.textContent='CHECKING…';try{await purgeOldRuntime();const u=`https://raw.githubusercontent.com/Swoop081/nba-gm/main/version.json?force=${Date.now()}`;const res=await fetch(u,{cache:'no-store',headers:{'cache-control':'no-cache'}});if(!res.ok)throw new Error('Version check failed');const live=await res.json();if(!live?.version)throw new Error('Invalid version');if(live.version===VERSION){button.textContent=`UP TO DATE — v${VERSION}`;setTimeout(()=>{button.textContent=original;button.disabled=false;button.onclick=e=>checkForUpdate(e.currentTarget)},2200);return}button.textContent=`UPDATE NOW — v${live.version}`;button.disabled=false;button.onclick=()=>hardUpdate(live.version,button)}catch(e){button.textContent='CHECK FAILED — TAP TO RETRY';button.disabled=false;button.onclick=e=>checkForUpdate(e.currentTarget)}}
const updateButton=document.querySelector('#launchCheckUpdate');if(updateButton)updateButton.onclick=e=>checkForUpdate(e.currentTarget);
addEventListener('load',async()=>{await purgeOldRuntime();await registerUpdater()});
