const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const pick=(arr,w)=>{let s=w.reduce((a,b)=>a+b,0),r=Math.random()*s;for(let i=0;i<arr.length;i++){r-=w[i];if(r<=0)return arr[i]}return arr.at(-1)};
const val=(p,k,d=60)=>Number.isFinite(p?.ratings?.[k])?p.ratings[k]:d;
function tendencies(p){const three=val(p,'threePointShot'),rim=(val(p,'layup')+val(p,'drivingDunk')+val(p,'standingDunk'))/3,mid=(val(p,'midRangeShot')+val(p,'postFade'))/2,create=(val(p,'ballHandle')+val(p,'passVision')+val(p,'speedWithBall'))/3;return{usage:Math.max(25,val(p,'offensiveConsistency')*.55+val(p,'shotIQ')*.25+create*.2),three:Math.max(5,three-35),rim:Math.max(8,rim-30),mid:Math.max(4,mid-42),pass:Math.max(5,(val(p,'passVision')+val(p,'passIQ'))/2-25)}}
function stat(){return{min:0,pts:0,fgm:0,fga:0,tpm:0,tpa:0,ftm:0,fta:0,orb:0,drb:0,reb:0,ast:0,stl:0,blk:0,tov:0,pf:0}}
function lineup(team){return [...team].sort((a,b)=>(b.rating2k||0)-(a.rating2k||0)).slice(0,10)}
function chooseShooter(team){return pick(team,team.map(p=>tendencies(p).usage))}
function chooseDefender(team,shot){const key=shot==='rim'?'interiorDefense':'perimeterDefense';return pick(team,team.map(p=>Math.max(10,val(p,key))))}
function shotType(p){const t=tendencies(p);return pick(['three','rim','mid'],[t.three,t.rim,t.mid])}
function makeChance(p,d,type,fatigue=0){const atk=type==='three'?val(p,'threePointShot'):type==='mid'?val(p,'midRangeShot'):(val(p,'layup')+val(p,'closeShot')+val(p,'drivingDunk'))/3;const def=type==='rim'?(val(d,'interiorDefense')+val(d,'block'))/2:val(d,'perimeterDefense');const base=type==='three'?.355:type==='mid'?.425:.59;return clamp(base+(atk-75)*.0035-(def-75)*.0024-fatigue*.002,.22,type==='rim'?.78:.62)}
export function simulateGame(home,away){const H=lineup(home),A=lineup(away),box=new Map([...H,...A].map(p=>[p.name,stat()]));const score={home:0,away:0};const possessions=96+Math.floor(Math.random()*13);for(const p of H)box.get(p.name).min=p===H[0]?36:Math.round(18+Math.random()*16);for(const p of A)box.get(p.name).min=p===A[0]?36:Math.round(18+Math.random()*16);
 function poss(off,def,side){const s=chooseShooter(off),ss=box.get(s.name),d=chooseDefender(def,'mid'),ds=box.get(d.name);const steal=(val(d,'steal')+val(d,'passPerception'))/2;if(Math.random()<clamp(.105+(steal-70)*.0008-(val(s,'ballHandle')-70)*.0005,.07,.16)){ss.tov++;ds.stl++;return}const type=shotType(s),guard=chooseDefender(def,type),gs=box.get(guard.name);if(Math.random()<clamp(.12+(val(s,'drawFoul')-70)*.001-(val(guard,'defensiveConsistency')-70)*.0003,.07,.22)){const n=type==='three'?3:2;ss.fta+=n;for(let i=0;i<n;i++)if(Math.random()<clamp(.58+(val(s,'freeThrow')-60)*.004,.5,.94)){ss.ftm++;ss.pts++;score[side]++}gs.pf++;return}ss.fga++;if(type==='three')ss.tpa++;const made=Math.random()<makeChance(s,guard,type);if(made){ss.fgm++;const pts=type==='three'?3:2;if(type==='three')ss.tpm++;ss.pts+=pts;score[side]+=pts;const passer=pick(off,off.map(p=>p===s?1:tendencies(p).pass));if(passer!==s&&Math.random()<clamp(.48+(val(passer,'passVision')-70)*.004,.35,.78))box.get(passer.name).ast++;return}if(type!=='three'&&Math.random()<clamp(.045+(val(guard,'block')-65)*.0025,.02,.18))gs.blk++;const offensive=Math.random()<.235;if(offensive){const r=pick(off,off.map(p=>Math.max(5,val(p,'offensiveRebound'))));const rs=box.get(r.name);rs.orb++;rs.reb++}else{const r=pick(def,def.map(p=>Math.max(5,val(p,'defensiveRebound'))));const rs=box.get(r.name);rs.drb++;rs.reb++}}
 for(let i=0;i<possessions;i++){poss(H,A,'home');poss(A,H,'away')}return{score,possessions,box:[...box.entries()].map(([name,s])=>({name,...s}))}}
